version: "3.8"
services:
  jupyter:
    container_name: jupyter
    build:
      context: .
    ports:
      - "8888:8888"
    restart: "always"
    env_file:
      - jupyter.env
    volumes:
      - ./src:/home/jovyan/src
  neo4j:
    image: neo4j:4.0.3
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
    volumes:
      - ./neo4j/plugins:/plugins
    environment:
      NEO4j_AUTH: ${NEO_AUTH}
    restart: always